/* eslint-disable prettier/prettier */
/* FILE GENERATED AUTOMATICALLY */

export type BuddyType =
    | "Task Force 809 Buddy"
    | "Beckoner Buddy"
    | "RGX 11z Pro Buddy"
    | "RGX 11z Pro, Ep 4 Buddy"
    | "RGX 11z Pro, Ep 9 Buddy"
    | "Cruiser Buddy"
    | "Big Announcement Buddy"
    | "Altitude Buddy"
    | "Frequency Buddy"
    | "Anansi Buddy"
    | "Divergence Buddy"
    | "Araxys Buddy"
    | "Araxys, Ep 9 Buddy"
    | "Epilogue: Apple a Day Buddy"
    | "Neptune Buddy"
    | "Neptune, V25 Buddy"
    | "Gaia's Vengeance Buddy"
    | "Gaia's Vengeance, Ep 7 Buddy"
    | "Celestia Buddy"
    | "Zedd Buddy"
    | "Get Carried Buddy"
    | "Composite Buddy"
    | "Alley-oop Buddy"
    | "Epilogue: Alley-oop Buddy"
    | "Night Guard Buddy"
    | "Bazooka Badger Buddy"
    | "Bumble Brigade Buddy"
    | "Beta Key Buddy"
    | "Big Brain Buddy"
    | "In A Bind Buddy"
    | "Year One Buddy"
    | "Apple a Day Buddy"
    | "BlastX Buddy"
    | "Blueberry Buddy"
    | "Boba Truck Buddy"
    | "Boba Buddy"
    | "Bolt Buddy"
    | "Prize Size KAY/O Buddy"
    | "Epilogue: Prize Size KAY/O Buddy"
    | "Nazar Bead Buddy"
    | "Hammer Time Buddy"
    | "Big ol' Barrel Buddy"
    | "Easy Breezy Buddy"
    | "Ornamental Commander Buddy"
    | "Bruno Coin Buddy"
    | "Epilogue: Bruno Coin Buddy"
    | "Eco the Bulldog Buddy"
    | "Epilogue: Eco the Bulldog Buddy"
    | "Bullet Buddy"
    | "Call Me Buddy"
    | "Closed Beta Coin Buddy"
    | "Nanowire Cartridge Buddy"
    | "Desert Rose Buddy"
    | "Crunch the Numbers Buddy"
    | "Get The Picture Buddy"
    | "Let It Cook Buddy"
    | "Edible Ornament Buddy"
    | "Candy Cutie Buddy"
    | "Canteen Buddy"
    | "Sneaky Kitty Buddy"
    | "Overlay Buddy"
    | "Misilito Buddy"
    | "Cat-Eye Buddy"
    | "Claw Tactics: Dan Buddy "
    | "Champions 2024 Buddy"
    | "VALORANT GO! Vol. 1 Cypher Buddy"
    | "VALORANT GO! Vol. 1 Jett Buddy"
    | "VALORANT GO! Vol. 1 Killjoy Buddy"
    | "VALORANT GO! Vol. 2 Phoenix Buddy"
    | "VALORANT GO! Vol. 2 Raze Buddy"
    | "VALORANT GO! Vol. 1 Reyna Buddy"
    | "VALORANT GO! Vol. 1 Sage Buddy"
    | "VALORANT GO! Vol. 2 Sova Buddy"
    | "VALORANT GO! Vol. 2 Viper Buddy"
    | "VALORANT GO! Vol. 2 Yoru Buddy"
    | "Winner Winner Buddy"
    | "Chilling Nugget Buddy"
    | "Good Luck Knot Buddy"
    | "Chicken Out Buddy"
    | "Origin Buddy"
    | "Blast Pin Buddy"
    | "Killer Frog Buddy"
    | "Island Dreams Buddy"
    | "Rune Stone Buddy"
    | "EP 1 // 1 Coin Buddy"
    | "EP 1 // 2 Coin Buddy"
    | "EP 1 // 3 Coin Buddy"
    | "EP 2 // 1 Coin Buddy"
    | "EP 2 // 2 Coin Buddy"
    | "EP 2 // 3 Coin Buddy"
    | "EP 3 // 1 Coin Buddy"
    | "Ep 3 // 2 Coin Buddy"
    | "Ep 3 // 3 Coin Buddy"
    | "Ep 4 // 1 Coin Buddy"
    | "Ep 4 // 2 Coin Buddy"
    | "EP 4 // 3 Coin Buddy"
    | "Ep 5 // 1 Coin Buddy"
    | "Ep 5 // 2 Coin Buddy"
    | "Ep 5 // 3 Coin Buddy"
    | "Ep 6 // 1 Coin Buddy"
    | "Ep 6 // 2 Coin Buddy"
    | "Ep 6 // 3 Coin Buddy"
    | "Ep 7 // 1 Coin Buddy"
    | "Ep 7 // 2 Coin Buddy"
    | "Ep 7 // 3 Coin Buddy"
    | "Ep 8 // 1 Coin Buddy"
    | "Ep 8 // 2 Coin Buddy "
    | "Ep 8 // 3 Coin Buddy"
    | "Ep 9 // 1 Coin Buddy"
    | "Ep 9 // 2 Coin Buddy"
    | "Ep 9 // 3 Coin Buddy"
    | "V25 ACT I Coin Buddy"
    | "V25 ACT II Coin Buddy"
    | "V25 ACT III Coin Buddy"
    | "Comet Buddy"
    | "Follow Me Buddy"
    | "Shell Song Buddy"
    | "Epilogue: Shell Song Buddy"
    | "Corbin's Light Buddy"
    | "Chilly McFreeze Buddy"
    | "Bulletbox Buddy"
    | "Nocturnum Buddy"
    | "Completely Cracked Buddy"
    | "Crate Buddy"
    | "Radianite Crate Buddy"
    | "Red Alert Buddy"
    | "Cup o' Crown Buddy"
    | "Prime Time Buddy"
    | "Slurp Buddy"
    | "Arcane Cupcake Buddy"
    | "Electric Love Buddy"
    | "Divine Swine Buddy"
    | "Doom Wing Buddy"
    | "Potted Pal Buddy"
    | "Doombringer Buddy"
    | "Glitchpop Buddy"
    | "Glitchpop, EP 2 Buddy"
    | "Champions 2022 Dad Hat Buddy"
    | "ChronoVoid Buddy"
    | "Dalgona Coffee Buddy"
    | "Dance Fever Buddy"
    | "Danger Lizard Buddy"
    | "Shoot Here Buddy"
    | "Daruma Charm Buddy"
    | "Prelude to Chaos Buddy"
    | "Lucky Dice Buddy"
    | "Discotech Buddy"
    | "Epilogue: Discotech Buddy"
    | "Outlaw Buddy"
    | "Donut Buddy"
    | "Elderflame Buddy"
    | "Message in a Bottle Buddy"
    | "Ion, Ep5 Buddy"
    | "VLT/R Buddy"
    | "Ragna-Rock Out Buddy"
    | "Ducky on Swing Buddy"
    | "Happy Dumpling Buddy"
    | "Dumpster Fire Buddy"
    | "Epilogue: Dumpster Fire Buddy"
    | "Imperium Buddy"
    | "Egg in a Basket Buddy"
    | "Singularity Buddy"
    | "Singularity, Ep 9 Buddy"
    | "Sunny Side Buddy"
    | "Epilogue: Sunny Side Buddy"
    | "Music Electric Buddy"
    | "Songsteel Buddy"
    | "Together Forever Buddy"
    | "Champions Cube Buddy"
    | "VCT LOCK//IN Winner Buddy"
    | "VCT Champions Winner Buddy"
    | "VCT Masters Winner Buddy"
    | "VCT 2021 Spark Buddy"
    | "Good Boy, Bruno Buddy"
    | "Venturi Buddy"
    | "Nice Smile Buddy"
    | "Nightmare Toes Buddy"
    | "Hundreds and Thousands Buddy"
    | "Forsaken Buddy"
    | "Scaredy Cow Buddy"
    | "Epilogue: Scaredy Cow Buddy"
    | "Ups and Downs Buddy"
    | "Velocity Buddy"
    | "Topotek Buddy"
    | "K.nock O.ut!! Buddy"
    | "Lunar Firework Buddy"
    | "Ascent Rising Buddy"
    | "Arcane Poro Buddy"
    | "Team Ace Buddy"
    | "KNG Meridian Buddy"
    | "Deep Divisions Buddy"
    | "Le Baguette Buddy"
    | "Kiss the Frog Buddy"
    | "Froggie Hat Buddy"
    | "Spectrum Buddy"
    | "Tactical Surprise Buddy"
    | "Game Changers Winner Buddy"
    | "Game Changers Trophy Buddy"
    | "Penguin Surprise Buddy"
    | "Epilogue: Penguin Surprise Buddy"
    | "Justice Served Buddy"
    | "Gelato Cutie Buddy"
    | "Gimbap Buddy"
    | "Tall Tales Buddy"
    | "Give Back Buddy"
    | "Give Back // 2023 Buddy"
    | "Give Back // 2024 Buddy"
    | "Give Back // V25 Buddy"
    | "Terrarium Treasure Buddy"
    | "Shimmer Buddy"
    | "Caught Buddy"
    | "Gonggi Buddy"
    | "Pick 'Em Master: Gonggi Buddy"
    | "Ruin Watcher Buddy"
    | "Nanobreak Buddy"
    | "Memory Chip Buddy"
    | ".SYS Buddy"
    | "Hawko Buddy"
    | "White Hat Buddy"
    | "Neo Frontier Buddy"
    | "In and Out of Trouble Buddy"
    | "Halo Halo Buddy"
    | "Ready to Roll Buddy"
    | "Safe Haven Buddy"
    | "HAZ + MATT // Haz Buddy"
    | "HAZ + MATT // Matt Buddy"
    | "Xpert Comms Buddy"
    | "Primordium Buddy"
    | "Digihex Buddy"
    | "Hieroscape Buddy"
    | "EX.O Buddy"
    | "Chasing Clouds Buddy"
    | "Owl Charm Buddy"
    | "Hydrodip Buddy"
    | "Prime Buddy"
    | "Prime//2.0 Buddy"
    | "XERØFANG Buddy "
    | "Frozen Solid Buddy"
    | "Icy Crate Buddy"
    | "Bubble Pop Buddy"
    | "Premier Ignition Champion Buddy"
    | "Bound Buddy"
    | "Mi Goreng Buddy"
    | "VCT LOCK//IN Dad Hat Buddy"
    | "Jack O' Lantern Buddy"
    | "Sea Jelly Buddy"
    | "Retrowave Buddy"
    | "Cloudburst Soles Buddy"
    | "Jett's Windbreaker Buddy"
    | "Epilogue: Jett's Windbreaker Buddy"
    | "Yoonseul Buddy"
    | "Beary Good Fortune Buddy"
    | "Tactic Kappa Buddy"
    | "Give Back // 2022 Buddy"
    | "Extra Crispy Buddy"
    | "Heavy Lifting Buddy"
    | "The Key to Ancient Mysteries Buddy"
    | "Key of Life Buddy"
    | "Bot Buddy"
    | "Pocket Turret Buddy"
    | "Epilogue: Pocket Turret Buddy"
    | "Netter Treter Buddy"
    | "Ruination Buddy"
    | "K/TAC Buddy"
    | "Kingdom Logo Buddy"
    | "Kitsune Mask Buddy"
    | "Neural Pattern Buddy"
    | "Perfect Pattern Buddy"
    | "Bumble Stitch Buddy"
    | "Kohaku & Matsuba Buddy"
    | "Miss Spots Buddy"
    | "Lava Lamp Buddy"
    | "Lotus Buddy"
    | "Aemondir Buddy"
    | "Light Stick Buddy"
    | "Dance of Luck Buddy"
    | "Blush Buddy"
    | "Daydreams Buddy"
    | "Iridian Thorn Buddy"
    | "Star Lotus Buddy"
    | "GL Have Cat Buddy"
    | "New Year's Knot Buddy"
    | "Celestial Buddy"
    | "Arcane Enforcer Buddy"
    | "Magepunk Buddy"
    | "Magepunk, Ep 6 Buddy"
    | "Magic Hummingbird Buddy"
    | "Spline Buddy"
    | "On The Case Buddy"
    | "Magic Mance Buddy"
    | "Mango Tango Buddy"
    | "Aquatica Buddy "
    | "Sweet Victory Buddy"
    | "Pick 'Em Master: Sweet Victory Buddy"
    | "Time's Up Buddy"
    | "Dallah Buddy"
    | "Mic Drop Buddy"
    | "Bounce House Buddy"
    | "Mini Espresso Buddy"
    | "Monkey Business Buddy"
    | "Valiant Hero Buddy"
    | "Monster Cookie Buddy"
    | "Hot and Spicy Buddy"
    | "Drop the Hammer Buddy"
    | "Epilogue: Drop the Hammer Buddy"
    | "Mid-Autumn Sweet Buddy"
    | "Overdrive Buddy"
    | "Mummy Mance Buddy"
    | "Epilogue: Mummy Mance Buddy"
    | "Treble Clef Buddy"
    | "Epilogue: Treble Clef Buddy"
    | "Lightning Kicks Buddy"
    | "Matryoshka Buddy"
    | "Genesis Buddy"
    | "Salmon Nigiri Buddy"
    | "Moondash Buddy"
    | "Kuronami Buddy"
    | "Deadly Precision Buddy"
    | "Metal Petals Buddy"
    | "Libretto Buddy"
    | "Ion Buddy"
    | "Ancient Mysteries Revealed Buddy"
    | "VALORANT Coin Buddy"
    | "Oni Buddy"
    | "Oni, Ep 6 Buddy"
    | "Keep it Safe Buddy"
    | "Keep it Safer Buddy"
    | "Venom Vial Buddy"
    | "Folded Wish Buddy"
    | "Epilogue: Folded Wish Buddy"
    | "Paracord Buddy"
    | "Peace and Love Buddy"
    | "Mother of Pearl Buddy"
    | "Dan the Penguin Buddy"
    | "Hot Bling Buddy"
    | "High Top Heat Buddy"
    | "Can't Break Me Buddy"
    | "Ping Pong Buddy"
    | "Hue Shift Buddy"
    | "Old Salt Buddy"
    | "Pocket Jett Buddy"
    | "Pocket Sage Buddy"
    | "Pizza Buddy"
    | "Pint-Size Planet Buddy"
    | "Magepunk, Ep 3 Buddy"
    | "Snap Trap Buddy"
    | "POLYfox Buddy"
    | "Rubber Ducky Buddy"
    | "Brimsicle Buddy"
    | "Artisan Buddy"
    | "Take on the Tundra Buddy"
    | "PREMIER E7A3 CHAMPION // ADV BUDDY"
    | "PREMIER E7A3 CHAMPION // CTD BUDDY"
    | "PREMIER E7A3 CHAMPION // ELT BUDDY "
    | "PREMIER E7A3 CHAMPION // INT BUDDY"
    | "PREMIER E7A3 CHAMPION // OPN BUDDY"
    | "Premier Launch Champion // Adv Buddy"
    | "Premier Launch Champion // Ctd Buddy"
    | "Premier Launch Champion // Elt Buddy "
    | "Premier Launch Champion // Int Buddy"
    | "Premier Launch Champion // Opn Buddy"
    | "PREMIER E8A1 CHAMPION // ADV Buddy"
    | "PREMIER E8A1 CHAMPION // CTD Buddy"
    | "PREMIER E8A1 CHAMPION // ELT Buddy"
    | "PREMIER E8A1 CHAMPION // INT Buddy"
    | "PREMIER E8A1 CHAMPION // OPN Buddy"
    | "PREMIER E8A2 CHAMPION // ADV Buddy"
    | "PREMIER E8A2 CHAMPION // CTD Buddy"
    | "PREMIER E8A2 CHAMPION // ELT Buddy"
    | "PREMIER E8A2 CHAMPION // INT Buddy"
    | "PREMIER E8A2 CHAMPION // OPN Buddy"
    | "PREMIER E8A3 CHAMPION // ADV Buddy"
    | "PREMIER E8A3 CHAMPION // CTD Buddy"
    | "PREMIER E8A3 CHAMPION // ELT Buddy"
    | "PREMIER E8A3 CHAMPION // INT Buddy"
    | "PREMIER E8A3 CHAMPION // OPN Buddy"
    | "PREMIER E9A1 CHAMPION // ADV Buddy"
    | "PREMIER E9A1 CHAMPION // CTD Buddy"
    | "PREMIER E9A1 CHAMPION // ELT Buddy"
    | "PREMIER E9A1 CHAMPION // INT Buddy"
    | "PREMIER E9A1 GRAND CHAMP Buddy"
    | "PREMIER E9A1 CHAMPION // OPN Buddy"
    | "PREMIER E9A2 CHAMPION // ADV Buddy"
    | "PREMIER E9A2 CHAMPION // CTD Buddy"
    | "PREMIER E9A2 CHAMPION // ELT Buddy"
    | "PREMIER E9A2 CHAMPION // INT Buddy"
    | "PREMIER E9A2 GRAND CHAMP Buddy"
    | "PREMIER E9A2 CHAMPION // OPN Buddy"
    | "PREMIER E9A3 CHAMPION // ADV Buddy"
    | "PREMIER E9A3 CHAMPION // CTD Buddy"
    | "PREMIER E9A3 CHAMPION // ELT Buddy"
    | "PREMIER E9A3 CHAMPION // INT Buddy"
    | "PREMIER E9A3 GRAND CHAMP Buddy"
    | "PREMIER E9A3 CHAMPION // OPN Buddy"
    | "PREMIER V25A1 CHAMPION // ADV Buddy"
    | "PREMIER V25A1 CHAMPION // CTD Buddy"
    | "PREMIER V25A1 CHAMPION // ELT Buddy"
    | "PREMIER V25A1 CHAMPION // INT Buddy"
    | "PREMIER V25A1 GRAND CHAMP Buddy"
    | "PREMIER V25A1 CHAMPION // OPN Buddy"
    | "PREMIER V25A2 CHAMPION // ADV Buddy"
    | "PREMIER V25A2 CHAMPION // CTD Buddy"
    | "PREMIER V25A2 CHAMPION // ELT Buddy"
    | "PREMIER V25A2 CHAMPION // INT Buddy"
    | "PREMIER V25A2 GRAND CHAMP Buddy"
    | "PREMIER V25A2 CHAMPION // OPN Buddy"
    | "Pay Respects Buddy"
    | "One Direction Buddy"
    | "Twisted Treat Buddy "
    | "Epilogue: Twisted Treat Buddy "
    | "Flyby Hug Buddy"
    | "Pride Buddy"
    | "Bear Hug Buddy"
    | "Protocol 781-A Buddy"
    | "Original Protractor Buddy"
    | "Lovebyte Gun Buddy"
    | "Lucky Rabbit Buddy"
    | "Radianite Crystal Buddy"
    | "Late Night Calories Buddy"
    | "EP1: Bronze Buddy"
    | "EP1: Diamond Buddy"
    | "EP1: Gold Buddy"
    | "EP1: Immortal Buddy"
    | "EP1: Iron Buddy"
    | "EP1: Platinum Buddy"
    | "EP1: Radiant Buddy"
    | "EP1: Silver Buddy"
    | "EP2: Bronze Buddy"
    | "EP2: Diamond Buddy"
    | "EP2: Gold Buddy"
    | "EP2: Immortal Buddy"
    | "EP2: Iron Buddy"
    | "EP2: Platinum Buddy"
    | "EP2: Radiant Buddy"
    | "EP2: Silver Buddy"
    | "EP3: Bronze Buddy"
    | "EP3: Diamond Buddy"
    | "EP3: Gold Buddy"
    | "EP3: Immortal Buddy"
    | "EP3: Iron Buddy"
    | "EP3: Platinum Buddy"
    | "EP3: Radiant Buddy"
    | "EP3: Silver Buddy"
    | "EP4: Bronze Buddy"
    | "EP4: Diamond Buddy"
    | "EP4: Gold Buddy"
    | "EP4: Immortal Buddy"
    | "EP4: Iron Buddy"
    | "EP4: Platinum Buddy"
    | "EP4: Radiant Buddy"
    | "EP4: Silver Buddy"
    | "EP5: Ascendant Buddy"
    | "EP5: Bronze Buddy"
    | "EP5: Diamond Buddy"
    | "EP5: Gold Buddy"
    | "EP5: Immortal Buddy"
    | "EP5: Iron Buddy"
    | "EP5: Platinum Buddy"
    | "EP5: Radiant Buddy"
    | "EP5: Silver Buddy"
    | "EP6: Ascendant Buddy"
    | "EP6: Bronze Buddy"
    | "EP6: Diamond Buddy"
    | "EP6: Gold Buddy"
    | "EP6: Immortal Buddy"
    | "EP6: Iron Buddy"
    | "EP6: Platinum Buddy"
    | "EP6: Radiant Buddy"
    | "EP6: Silver Buddy"
    | "EP7: Ascendant Buddy"
    | "EP7: Bronze Buddy"
    | "EP7: Diamond Buddy"
    | "EP7: Gold Buddy"
    | "EP7: Immortal Buddy"
    | "EP7: Iron Buddy"
    | "EP7: Platinum Buddy"
    | "EP7: Radiant Buddy"
    | "EP7: Silver Buddy"
    | "EP8: Ascendant Buddy"
    | "EP8: Bronze Buddy"
    | "EP8: Diamond Buddy"
    | "EP8: Gold Buddy"
    | "EP8: Immortal Buddy"
    | "EP8: Iron Buddy"
    | "EP8: Platinum Buddy"
    | "EP8: Radiant Buddy"
    | "EP8: Silver Buddy"
    | "EP9: Ascendant Buddy"
    | "EP9: Bronze Buddy"
    | "EP9: Diamond Buddy"
    | "EP9: Gold Buddy"
    | "EP9: Immortal Buddy"
    | "EP9: Iron Buddy"
    | "EP9: Platinum Buddy"
    | "EP9: Radiant Buddy"
    | "EP9: Silver Buddy"
    | "Gravitational Uranium Neuroblaster Buddy"
    | "Laser Blaster Buddy"
    | "Slay Ride Buddy"
    | "Panoramic Buddy"
    | "Spoonful Buddy"
    | "Stardust Buddy"
    | "Robotic Companion Buddy"
    | "Mini Mecha Buddy"
    | "Epilogue: Mini Mecha Buddy"
    | "Flash Blades Buddy"
    | "Root Beer Buddy"
    | "Immortal Rose Buddy"
    | "Sentinels of Light, Ep 7 Buddy"
    | "Salt Shaker Buddy"
    | "Epilogue: Salt Shaker Buddy"
    | "Ancient Inheritance Buddy"
    | "Dog Tags Buddy"
    | "Sunset Scoot Buddy"
    | "Death Stalker Buddy"
    | "Seal of Approval Buddy"
    | "Peripherals Buddy"
    | "Silhouette Buddy"
    | "Fishbones Buddy"
    | "Shellspire Buddy"
    | "Sheng Jian Bao Buddy"
    | "Pocket Sized Sheriff Buddy"
    | "Epilogue: Pocket Sized Sheriff Buddy"
    | "Knight's Market Buddy"
    | "Ebi Nigiri Buddy"
    | "Swinging Shumai Buddy"
    | "Lycan's Bane Buddy"
    | "Transition Buddy"
    | "Byteshift Buddy"
    | "Sleepy Bruno Buddy"
    | "Slime Mosh Buddy"
    | "All-purpose Slipper Buddy"
    | "Smite Knife Buddy"
    | "Golden Smite Knife Buddy"
    | "Metal Wings Buddy"
    | "Toque Buddy"
    | "Helix Buddy"
    | "Sloth Tactics Buddy"
    | "Winter Whisper Buddy"
    | "Snowbro Buddy"
    | "Snowfall Buddy"
    | "Sentinels of Light Buddy"
    | "Reaver Buddy"
    | "Reaver, EP 5 Buddy"
    | "Sovereign Buddy"
    | "Sovereign, Ep 8 Buddy"
    | "Space Out Homie Buddy"
    | "Hot Take Buddy"
    | "The Spike Buddy"
    | "Spike Rush Buddy"
    | "Mystbloom Buddy"
    | "Split Decision Buddy"
    | "Battle Crab Buddy"
    | "Surge Protector Buddy"
    | "Squish Ball Buddy"
    | "Lucky Star Buddy"
    | "Epilogue: Lucky Star Buddy"
    | "Dream Charm Buddy"
    | "Dimensional Fragment Buddy"
    | "Sock of Cheer Buddy"
    | "Spellbound Buddy"
    | "Tilde Buddy"
    | "Refractrix Buddy"
    | "Head in the Clouds Buddy"
    | "Riptide Buddy"
    | "Cheesed Buddy"
    | "CYRAX Buddy"
    | "On The Low Buddy"
    | "Astro Bear Buddy"
    | "Boxing TactiBear Buddy"
    | "Bear Tactics Buddy"
    | "Hula Bear Buddy"
    | "Bunny Tactics Buddy"
    | "UltraBright Torch Buddy"
    | "Cat Tactics Buddy"
    | "Tacti-Force Obsidian Buddy"
    | "Tacti-Force Ruby Buddy"
    | "Tacti-Force Topaz Buddy"
    | "Tacti-Force Sapphire Buddy"
    | "Tacti-Force Emerald Buddy"
    | "Hang Time Buddy"
    | "Squirrel Tactics Buddy"
    | "Potato Aim Buddy"
    | "Mr.Takoyaki Buddy"
    | "Tanghulu Buddy"
    | "Prism Buddy"
    | "Sample 36-K Buddy"
    | "Radianite Orb Buddy"
    | "Tigris Buddy"
    | "Fortune Paws Buddy"
    | "Toaster Buddy"
    | "NO LIMITS Buddy"
    | "Octobuddy Buddy"
    | "Scuttle Trash Buddy"
    | "Fist Bump Buddy"
    | "Sandswept Buddy"
    | "Champions 2022 Buddy"
    | "Turtle Ship Buddy"
    | "No. 1 Fan Buddy"
    | "Tower of Power Buddy"
    | "Outta This World Buddy"
    | "\"I Create\" Buddy"
    | "Exquisitely Wrapped Buddy"
    | "Stringed Soprano Buddy"
    | "Wonderstallion Buddy"
    | "Ego Buddy"
    | "Utility Belt Buddy"
    | "VCT 2025 Americas Buddy"
    | "VCT 2025 CN Buddy"
    | "VCT 2025 EMEA Buddy"
    | "VCT 2025 Pacific Buddy"
    | "VCT x 100T Buddy"
    | "VCT x AG Buddy"
    | "VCT x BBL Buddy"
    | "VCT x BLD Buddy"
    | "VCT x BLG Buddy"
    | "VCT x C9 Buddy"
    | "VCT x DFM Buddy"
    | "VCT x DRG Buddy"
    | "VCT x DRX Buddy"
    | "VCT x EDG Buddy"
    | "VCT x EG Buddy"
    | "VCT x FNC Buddy"
    | "VCT x FPX Buddy"
    | "VCT x FUR Buddy"
    | "VCT x FUT Buddy"
    | "VCT x G2 Buddy"
    | "VCT x GEN Buddy"
    | "VCT x GE Buddy"
    | "VCT x GX Buddy"
    | "VCT x JDG Buddy"
    | "VCT x KC Buddy"
    | "VCT x KOI Buddy"
    | "VCT x KRÜ Buddy"
    | "VCT x LEV Buddy"
    | "VCT x LOUD Buddy"
    | "VCT x M8 Buddy"
    | "VCT x MIBR Buddy"
    | "VCT x NAVI Buddy"
    | "VCT x NOVA Buddy"
    | "VCT x NRG Buddy"
    | "VCT x PRX Buddy"
    | "VCT x RRQ Buddy"
    | "VCT x SEN Buddy"
    | "VCT x T1 Buddy"
    | "VCT x TE Buddy"
    | "VCT x TEC Buddy"
    | "VCT x TH Buddy"
    | "VCT x TL Buddy"
    | "VCT x TLN Buddy"
    | "VCT x TS Buddy"
    | "VCT x TYL Buddy"
    | "VCT x VIT Buddy"
    | "VCT x WOL Buddy"
    | "VCT x ZETA Buddy"
    | "VCT x 2G Buddy"
    | "VCT x APK Buddy"
    | "VCT x BOOM Buddy"
    | "VCT x NS Buddy"
    | "VCT x XLG Buddy"
    | "Duo's Day Buddy"
    | "5 Years Buddy"
    | "The Wheel of Steel Buddy"
    | "Soul Capsule Buddy"
    | "Solarex Buddy"
    | "Holomoku Buddy"
    | "Walis Tambo Buddy"
    | "Luna Buddy"
    | "Melondramatic Buddy"
    | "Epilogue: Melondramatic Buddy"
    | "White Snake Buddy"
    | "Grim Delight Buddy"
    | "Pocket Knife Buddy"
    | "Convergence Buddy"
    | "PlayZilla Trick Master Buddy"
    | "Dimensional Drip Buddy"
    | "Zoomer Pop Buddy";