/* eslint-disable prettier/prettier */
/* FILE GENERATED AUTOMATICALLY */

export type SprayType =
    | "Caught on Camera Spray"
    | "Chicken Out Spray"
    | "Defy the Limits Spray"
    | "G.O.A.T. Spray"
    | "Sad Crab Spray"
    | "No Time Spray"
    | "No Toxicity Spray"
    | "Dark Side Beyond Spray"
    | "Dap Team Spray"
    | "This is Also Fine Spray"
    | "Little Onion Lad Spray"
    | "Cheaters Never Prosper Spray"
    | "Wanted: Tactibunny Spray"
    | "8-bit VALORANT Spray"
    | "GGWP Spray"
    | "Mic Drop Spray"
    | "Step Under Here Spray"
    | "No Op Spray"
    | "Piece of Cake Spray"
    | "Pick My Strat Spray"
    | "Octorave Spray"
    | "Stellar Dendrite Spray"
    | "Thumbs Up Spray"
    | "Stay Safe, Wash Your Hands Spray"
    | "RGX 11z Pro Spray"
    | "RGX 11z Pro, Ep 4 Spray"
    | "RGX 11z Pro, Ep 9 Spray"
    | "Fierce Form Spray"
    | "Gekko Spray"
    | "Creature Crew Spray"
    | "Here I Am Spray"
    | "Bazooka Badger Spray"
    | "Dance Fever Spray"
    | "K.nock O.ut!! Spray"
    | "Gaia's Vengeance Spray"
    | "Gaia's Vengeance, Ep 7 Spray"
    | "Spectrum Spray"
    | "Bolt Spray"
    | "Boom! Spray"
    | "Fade Spray"
    | "On the Prowl Spray"
    | "Eye Opener Spray"
    | "Breach Spray"
    | "K.O. Spray"
    | "Guns Out Spray"
    | "FTW Spray"
    | "Ignite: Huang Spray"
    | "Ignite: Feng Spray "
    | "Cypher Figure Spray"
    | "Killjoy Figure Spray"
    | "Jett Figure Spray"
    | "Sage Figure Spray"
    | "Deadlock Spray"
    | "Crossed Wires Spray"
    | "Cyber Oak Spray"
    | "Camper Spray"
    | "Tejo Spray"
    | "Heat Wave Spray"
    | "Ordinance Request Spray"
    | "Excuse Me? Spray"
    | "Steal The Win Spray"
    | "Gekko Diff Spray"
    | "Champions 2024 Spray"
    | "Octobuddy Spray"
    | "Cheesy Shot Spray"
    | "Raze Spray"
    | "BoomShaka Spray"
    | "Bombshell Spray"
    | "Round Start Spray"
    | "Explorgi Spray"
    | "Nocturnum Spray"
    | "Doombringer Spray"
    | "ChronoVoid Spray"
    | "Danger Spray"
    | "One In The Chamber Spray"
    | "Chamber Spray"
    | "Seeing Double Spray"
    | "VALORANT Spray"
    | "Prelude to Chaos Spray"
    | "Bruno Coin Spray"
    | "Doodle Buds // Tactifriends Spray"
    | "Doodle Buds // League of Legends Spray"
    | "Doodle Buds // Agents Spray"
    | "Elderflame Spray"
    | "Quack!! Spray"
    | "Imperium Spray"
    | "That's a Blowout Spray"
    | "A Perfect Score Spray"
    | "Just Jokin' Spray"
    | "Trailblazing Tiger Spray"
    | "Cool Joy Spray"
    | "Waddle Walk Spray"
    | "You Wanna Play? Spray"
    | "No Duelist No Problem Spray"
    | "Never Forget Leg Day Spray"
    | "Neon Bot Spray"
    | "No Spectre Spray"
    | "Nosey Neighbor Spray"
    | "Winner's Ribbon Spray"
    | "Sage Signal Spray"
    | "We Can Do It Spray"
    | "Dream Team Spray"
    | "Who's That Blind Spray"
    | "Definitely Not It Spray"
    | "Last Person Standing Spray"
    | "Perfectly Roasted Spray"
    | "Good Fortune Spray"
    | "Oh No Spray"
    | "No Bullets Spray"
    | "Network Error Spray"
    | "9 Lives Spray"
    | "No Worries Neon Spray"
    | "Shock Heart Spray"
    | "Drop Skin Please Spray"
    | "Gridcrash Spray"
    | "Oh Yes Spray"
    | "Blueberry Spray"
    | "Spicy Spray"
    | "Hershey Pup Spray"
    | "Choose my Weapon Spray"
    | "Glitch Out Chicken Spray"
    | "Make 'em Dance Spray"
    | "EZ Spray"
    | "Going C Spray"
    | "<3 Spray"
    | "Lit for 140 Spray"
    | "Faces in Places Spray"
    | "No Shorty Spray"
    | "Radianite Hazard Spray"
    | "What was that? Spray"
    | "Alas, poor Robot! Spray"
    | "Make Some Noise Spray"
    | "Chill Out Spray"
    | "Is This A Drone? Spray"
    | "Shhh! Spray"
    | "Do Not Enter Spray"
    | "Dumpster Fire Spray"
    | "/FF Spray"
    | "Epilogue: Super! Spray"
    | "Embarrassing! Spray"
    | "LAG! Spray"
    | "Happy Frog Spray"
    | "MY EYES! Spray"
    | "Revive Me, Jett! Spray"
    | "Super! Spray"
    | "Nope Spray"
    | "Approved! Spray"
    | "Lobster? Spray"
    | "Theo's Great Escape Spray"
    | "Bunny Hop Spray"
    | "Without a Trace Spray"
    | "Dabbing Dan Spray"
    | "Epilogue: Dabbing Dan Spray"
    | "Comedy and the Tragedy Spray"
    | "Songsteel Spray"
    | "Hang in There, Mance Spray"
    | "Nice Save Spray"
    | "Be Gone! Spray"
    | "No Odin Spray"
    | "This is Also Also Fine Spray"
    | "300 Spray"
    | "Walk! Don't Run Spray"
    | "Hardstuck Spray"
    | "Clutch or Kick Spray"
    | "Cracked Spray"
    | "Epilogue: Cracked Spray"
    | "Greatly Decreased? Spray"
    | "Sands of Time Spray"
    | "Killjoy! I Choose You! Spray"
    | "Max Money Spray"
    | "No Guardian Spray"
    | "No Pen Spray"
    | "Sand Sculpture Spray"
    | "Sova Says Sorry Spray"
    | "Surprised Penguin Spray"
    | "Pump Action Spray"
    | "Too Heavy Spray"
    | "Greatly Increased? Spray"
    | "Promises Kept Spray"
    | "Yikes Spray"
    | "Hooked Spray"
    | "Crispy Spray"
    | "Does Not Compute Spray"
    | "Hold Up Spray"
    | "Love > Hate Spray"
    | "Nice Try! Spray"
    | "No Judge Spray"
    | "OTL Spray"
    | "Artisan Spray"
    | "Trust in My Healing Spray"
    | "This is Not Fine Spray"
    | "To the Moon Spray"
    | "Not Impressed Spray"
    | "Volunteer Spray"
    | "Scavenger Spray"
    | "Mance on a Broom Go Zoom Spray"
    | "It's Lit Spray"
    | "Goldwing Spray"
    | "Countdown is On Spray"
    | "No Bucky Spray"
    | "With Love, Reyna Spray"
    | "Sad Yoru Spray"
    | "Trevor Gets It Spray"
    | "Turn it Up, Rudy Spray"
    | "Plant Plant Spray"
    | "Sugar Muffins Spray"
    | "Take My Creds! Spray"
    | "This is Really Not Fine Spray"
    | "Bad Hair Day Spray"
    | "Sweetest Match Spray"
    | "Head Slapper Spray"
    | "A Prime Valentine's Gift Spray"
    | "Hydrodip Spray"
    | "Jett-Bot Spray"
    | "Lost Connection Spray"
    | "Agent Down Spray"
    | "What's That? Spray"
    | "Potato Aim Spray"
    | "Missed a Spot Spray"
    | "Shoot Here Spray"
    | "Use Ult Spray"
    | "Woke Up Thinking Lineups Spray"
    | "Bruno's Happy Dance Spray"
    | "Hang Loose Spray"
    | "Crying Mance Spray"
    | "Capsule Collector Spray"
    | "All Aboard Spray"
    | "Matcha Break Spray"
    | "Pros Don't Fake Spray"
    | "Sheeeeesh Spray"
    | "Slipping Away Spray"
    | "Stop! Spray"
    | "Tactibear's Balalaika Spray"
    | "Take a Bow Spray"
    | "Many Thanks Spray"
    | "Splitting Melons Spray"
    | "#SAVEWIDEJOY Spray"
    | "Epilogue: #SAVEWIDEJOY Spray"
    | "Caution: Blinding Bird! Spray"
    | "Cap? No Cap? Spray"
    | "Bawk Bawk Brimstone Spray"
    | "Keeping Secrets Spray"
    | "Backseat Coaching Spray"
    | "Heaven or Hell? Spray"
    | "I Have Three Creds Spray"
    | "Charge Needed Spray"
    | "Look Behind You Spray"
    | "Coalition: Cobra Spray"
    | "Pretty Pretty Please Spray"
    | "It's Stinger Time Spray"
    | "Epilogue: It's Stinger Time Spray"
    | "Terrible Day for Rain Spray"
    | "Don't Watch This Spray"
    | "Skeptical Viper Spray"
    | "Immortalized Spray"
    | "Hide the Pain, Brimstone Spray"
    | "Piedra del Sol Spray"
    | "Unamused Chamber Spray"
    | "Phoenix Rise Spray"
    | "I've Been Hit Spray"
    | "Hehehehehe Spray"
    | "Let Me In Spray"
    | "No Sentinels Spray"
    | "Very Sneaky Spray"
    | "Raze has Range Spray"
    | "Guess That's It Spray"
    | "Blasting Away Spray"
    | "Choose Your Match Spray"
    | "You Are Here Spray"
    | "Sketchy AFK Spray"
    | "Simple Instructions Spray"
    | "Hawk Out Spray"
    | "Always Watching Spray"
    | "Fascinating Spray"
    | "Breach's Approval Spray"
    | "Mind Blown Spray"
    | "No Vision Spray"
    | "Treat Those Burns Spray"
    | "Fill Your Card Spray"
    | "I Sleep Spray"
    | "Written in the Stars Spray"
    | "See You Next Round Spray"
    | "Surprise! It's a Tiger Spray"
    | "Unconditional Surrender Spray"
    | "Huh? Spray"
    | "Dolla Dolla Bill Y'all Spray"
    | "Tug of War Spray"
    | "Wide Swing Spray"
    | "We Made it Spray"
    | "Well Played Spray"
    | "Omen Cat Dance Spray"
    | "Let's Go! Spray"
    | "Signature Spray"
    | "Charging Station Spray"
    | "Scoop of Smoke Spray"
    | "Wanted: Tactibear Spray"
    | "Bye Op Spray"
    | "Too Early for This Spray"
    | "Whaaat? Spray"
    | "Am I Clear? Spray"
    | "Peace Out Spray"
    | "Not Your Healer Spray"
    | "Nothing to See Here Spray"
    | "Bound Spray"
    | "Already Locked Spray"
    | "Don't Look Back Spray"
    | "Perfect Disaster Spray"
    | "Monstrocity Spray"
    | "I'm Melting Spray"
    | "Omen Remembers Spray"
    | "Moondash Spray"
    | "Put it on my Card Spray"
    | "Nice! Spray"
    | "Whack a Squirrel Spray"
    | "Composite Spray"
    | "Buy Me Spray"
    | "Vitality Vial Spray"
    | "Digihex Spray"
    | "You Did What Now? Spray"
    | "Close Call Spray"
    | "Blush Spray"
    | "Smoke Maze Spray"
    | "No Credit Spray"
    | "Keep It Cool Spray"
    | "Pumped Up Spray"
    | "Role Denial Spray"
    | "Pancake Pile-up Spray"
    | "Box Hijinks Spray"
    | "Rush Forward Spray"
    | "Crane Blossom Spray"
    | "Loyal Look Spray"
    | "Exit Wound Spray"
    | "Wave Rider Spray"
    | "The Great Responsibility Spray"
    | "Oh I See Spray"
    | "Techie's Trouble Spray"
    | "Scribble Squad Spray"
    | "Purrfect Pat Spray"
    | "Panoramic Spray"
    | "Roll On Spray"
    | "Transition Spray"
    | "Defuse Deception Spray"
    | "Freehand Spray"
    | "Power Punch Spray"
    | "There is Only One Truth Spray"
    | "Updraft Scare Spray"
    | "Ego Boost Spray"
    | "Spark Shock Spray"
    | "Splash Zone Spray"
    | "The Big Bet Spray"
    | "Fragger's Fall Spray"
    | "Libretto Spray"
    | "Penalty Call Spray"
    | "One Last Bite Spray"
    | "Silhouette Spray"
    | "Keep Your Paws Off Spray"
    | "Sandswept Spray"
    | "Hide'n Peek Spray"
    | "Break Time Spray"
    | "Journey Bear Spray"
    | "Tactiplay Spray"
    | "Just Another Wave Spray "
    | "Cup O' Crown Spray"
    | "Did You Drop This? Spray"
    | "Another Dream Team Spray"
    | "Savory Spice Spray"
    | "Scribble Blade Storm Spray "
    | "Let's Rotate Spray"
    | "Make It Rain Spray "
    | "Hearts Array Spray"
    | "Shocked Spark Spray "
    | "Cuteness Overload Spray"
    | "Hold Back Spray "
    | "Elegant Evade Spray "
    | "Awkward Breach Spray"
    | "Deep Breath Spray"
    | "Sentinel Slide Spray"
    | "Sending Love Spray"
    | "No Comment Spray"
    | "Aquatica Spray"
    | "Double Tap Spray"
    | "No Classic Spray "
    | "Downtime Spray"
    | "On My Own Spray"
    | "Shellspire Spray"
    | "Sneaky Stack Spray"
    | "Drink Up! Spray"
    | "UWU Spray"
    | "Caught One Spray"
    | "Sip of Joy Spray"
    | "Comet Spray"
    | "Where's My Knife? Spray"
    | "Boomtastic Spray"
    | "Tacti-Series Spray"
    | "No Bodyblock Spray"
    | "No Spray Spray"
    | "NO. 1 Fan Spray"
    | "Sure You Can Spray"
    | "Go Team Go Spray"
    | "Maybe Next Time Spray"
    | "Cloudweaver Spray"
    | "One Correct Answer Spray"
    | "Go Again? Spray"
    | "Wingman Wiggle Spray"
    | "Bumble Brigade Spray"
    | "We Did It Team Spray"
    | "Cover Me Spray"
    | "Guns On Me Spray"
    | "Blinded Again Spray"
    | "Bubble Pop Spray"
    | "Ultimate Shame Spray"
    | "Gotta One Tap Spray"
    | "Let Me Out Spray"
    | "Prowler Pop Spray"
    | "That's Terrifying Spray"
    | "Ain't My Time! Spray"
    | "Power of Five Spray"
    | "Dream Squad Spray"
    | "Convergence Spray"
    | "Frequency Spray"
    | "8 Bit Astra Spray"
    | "Overlay Spray"
    | "Silly Cat Spray"
    | "Great Big Hug Spray"
    | "Scheming Cypher Spray"
    | "So Fluffy Spray"
    | "Yoonseul Bear Spray"
    | "Yoonseul Frog Spray"
    | "Yoonseul Tiger Spray"
    | "Noted Spray"
    | "Around The Corner Spray"
    | "Focusing Spray"
    | "Bulletproof Armor Spray"
    | "Resting Wingman Spray"
    | "Cosmic Guide Spray"
    | "A Gift Spray"
    | "Winged Gift Spray"
    | "Bulletbox Spray"
    | "My Ult Orb Spray"
    | "Nanobreak Spray"
    | "Mosh O' Lantern Spray"
    | "No Controller Spray"
    | "Watch Them Run Spray"
    | "Pixel TactiBunny Spray"
    | "Requesting Reset Spray"
    | "Scribble Prowler Spray"
    | "Torque Spray"
    | "Lonely Viper's Pit Spray"
    | "Wanted: TactiPenguin Spray"
    | "Champions 2022 Jett Diff Spray"
    | "VCT 2021 Spark Spray"
    | "Fakeout Spray"
    | "Fist Bump Spray"
    | "A Fruitful New Year Spray"
    | "Team Ace // Jett Spray"
    | "Team Ace // Phoenix Spray"
    | "Team Ace // Raze Spray"
    | "Team Ace // Reyna Spray"
    | "Team Ace // Yoru Spray"
    | "GG Shooter Spray"
    | "GLHF Spray"
    | "Give Back // 2022 Spray"
    | "Give Back // 2023 Spray"
    | "Give Back // 2024 Spray"
    | "Give Back // V25 Spray"
    | "Drop It Spray"
    | "Googly Moogly Spray"
    | "KAY/O Spray"
    | "Drained Spray"
    | "Training Bot Spray"
    | "Wild Life Spray"
    | "On Your Trail Spray"
    | "Skye Spray"
    | "Cypher Spray"
    | "The Seeker Spray"
    | "I See You Spray"
    | "Neo Frontier Spray "
    | "Soulstrife Spray"
    | "Lethal Crosshair Spray"
    | "Calculated Spray"
    | "Primordium Spray"
    | "Sova Spray"
    | "Take Flight Spray"
    | "On Target Spray"
    | "Prime Brick Spray"
    | "Doomscrolling Spray"
    | "Jett Diff Spray"
    | "Killjoy Spray"
    | "Variable Removed Spray"
    | "Don't Cross Me Spray"
    | "Matsuba Spray"
    | "Kohaku Spray"
    | "Aemondir Spray"
    | "Lights Out Spray"
    | "Lucky Tiger Spray"
    | "Celestial Spray"
    | "BLAH Spray"
    | "Stay Hydrated Spray"
    | "Harbor Spray"
    | "That's a Six Spray"
    | "Magepunk, Ep 3 Spray"
    | "Claw and Order Spray"
    | "Champions 2022 Curse Spray"
    | "New Drip Spray"
    | "Flames in my Veins Spray"
    | "MEOW Spray"
    | "Runnin' on Empty Spray"
    | "Bust a Move Spray"
    | "Just Business Spray"
    | "Dabbing Duo Spray"
    | "Outlaw Spray"
    | "Sic' Em Spray"
    | "Give Back Spray"
    | "Party's Here Spray"
    | "Cake or Spike? Spray"
    | "Delightful Stretch Spray"
    | "TukTuk Spray"
    | "Sorry, Bro! Spray"
    | "Light 'Em Up Spray"
    | "Not Today Spray"
    | "All Yuck, No Yum Spray"
    | "Crystal Ball Spray"
    | "Ego or Eco Spray"
    | "Secret Sequence Spray"
    | "Shreddy Teddy Spray"
    | "Icebreaker Spray"
    | "Tacti-Force Spray"
    | "Pity Party Spray"
    | "Predicament Pals Spray"
    | "Dan the Champ Spray"
    | "Duo's Day: Left Spray"
    | "Duo's Day: Right Spray"
    | "Tag! You're Dead! Spray"
    | "Overdrive Spray"
    | "Crimsonbeast Spray"
    | "Valiant Hero Spray"
    | "Nice One Spray"
    | "Kuronami Spray"
    | "Vyse Spray"
    | "Arts and Crafts Spray"
    | "Jammed Spray"
    | "Octo Attack 2 Spray"
    | "Pick Your Poison Spray"
    | "Deadly Venom Spray"
    | "Viper Spray"
    | "Phoenix Spray"
    | "Claim the Crown Spray"
    | "Spotlight Spray"
    | "Too Easy Spray"
    | "Pocket Sage Spray"
    | "Protocol 781-A Spray"
    | "Clutch Spray"
    | "Astral Plane Spray"
    | "Astra Spray"
    | "Galaxy Brain Spray"
    | "Celestia Spray"
    | "Bullet Time Spray"
    | "Cabbage Seekers Spray"
    | "Ashamed Cat Spray"
    | "Nap Stack Tower Spray"
    | "Moon Scout Spray"
    | "Hieroscape Spray"
    | "It’s You and Me Spray"
    | "Scribble Speed Spray"
    | "Mosh Splat Spray"
    | "Whoops Spray"
    | "Hmph, Not Cool Spray"
    | "I Love This Gun Spray"
    | "Claws Are Out Spray"
    | "Revolving Door Spray"
    | "Guess That Stache Spray"
    | "Balisong Brandish Spray"
    | "Doom Wing Spray"
    | "Cry It Out Spray"
    | "Kill Contract Spray"
    | "I'm Outta Here Spray"
    | "No Escape Spray"
    | "Burn After Reading Spray"
    | "They Won’t Know Spray"
    | "Deadly Beauty Spray"
    | "Byteshift Spray"
    | "Spicy Prawn Spray"
    | "Refractrix Spray"
    | "Staying Shady Spray"
    | "Exterminated Spray"
    | "Balikbayan Box Spray"
    | "RIP Cypher Spray"
    | "Feeling Defeated Spray"
    | "Peeking Vents Spray"
    | "Gaming Gekko Spray"
    | "Jump Peek Jett Spray"
    | "Scribble Shock Dart Spray"
    | "Knives Only Spray"
    | "My Leg Spray"
    | "Night.Market Conspiracy Spray"
    | "Need To Reload Spray"
    | "The Raja Spray"
    | "Refreshing! Spray"
    | "Wingman For The Win Spray"
    | "Vyse Approved Spray"
    | "Sentinels of Light, Ep 7 Spray"
    | "Salt Shaker Spray"
    | "Brimstone Spray"
    | "The Big One Spray"
    | "Getting Reps Spray"
    | "Don't Ask Spray"
    | "Iso Spray"
    | "In the Zone Spray"
    | "Loose Cannon Spray"
    | "VALORANT GO! Vol. 1 Cypher Spray"
    | "VALORANT GO! Vol. 1 Jett Spray"
    | "VALORANT GO! Vol. 1 Killjoy Spray"
    | "VALORANT GO! Vol. 1 Reyna Spray"
    | "VALORANT GO! Vol. 1 Sage Spray"
    | "VALORANT GO! Vol. 2 Phoenix Spray"
    | "VALORANT GO! Vol. 2 Raze Spray"
    | "VALORANT GO! Vol. 2 Sova Spray"
    | "VALORANT GO! Vol. 2 Viper Spray"
    | "VALORANT GO! Vol. 2 Yoru Spray"
    | "Divergence Spray"
    | "Araxys Spray"
    | "Araxys, Ep 9 Spray"
    | "Neptune, V25 Spray"
    | "Champions 2022 Spray"
    | "Origin Spray"
    | "Glitchpop Spray"
    | "Glitchpop, EP 2 Spray"
    | "Singularity Spray"
    | "Singularity, Ep 9 Spray"
    | "VCT LOCK//IN Vamos! Spray"
    | "Forsaken Spray"
    | "Ruin Spray"
    | "EX.O Spray"
    | "Prime//2.0 Spray"
    | "XERØFANG Spray "
    | "Ruination Spray"
    | "Helix Spray"
    | "Magepunk Spray"
    | "Spline Spray"
    | "Ion Spray"
    | "Ion, Ep5 Spray"
    | "Oni Spray"
    | "Oni, Ep 6 Spray"
    | "Luna Spray"
    | "Gravitational Uranium Neuroblaster Spray"
    | "Sentinels of Light Spray"
    | "Reaver Spray"
    | "CYRAX Spray"
    | "Ego Spray"
    | "BlastX Spray"
    | "Clove Spray"
    | "Wee Punk Spray"
    | "Gloomheart Spray"
    | "Reaver, EP 5 Spray"
    | "Sovereign Spray"
    | "Sovereign, Ep 8 Spray"
    | "Mystbloom Spray"
    | "Clip It Spray"
    | "Neon Spray"
    | "Hot Mic Spray"
    | "Nice to Zap You Spray"
    | "Who's Next Spray"
    | "Sharp Spray"
    | "Yoru Spray"
    | "200 IQ Spray"
    | "Sip n' Spray"
    | "Tactibear Spray"
    | "Super Fan Spray"
    | "Infinite Reflections Spray"
    | "FTL Spray"
    | "Waylay Spray"
    | "Sage Spray"
    | "All Good Spray"
    | "Pulse Check Spray"
    | "Tigris Spray"
    | "None"
    | "Wonderstallion Spray"
    | "V for VALORANT Spray"
    | "Can't Teach That Spray"
    | "VCT x 100T Spray"
    | "VCT x BBL Spray"
    | "VCT x BLD Spray"
    | "VCT x C9 Spray"
    | "VCT x DFM Spray"
    | "VCT x DRX Spray"
    | "VCT x EG Spray"
    | "VCT x FNC Spray"
    | "VCT x FUR Spray"
    | "VCT x FUT Spray"
    | "VCT x G2 Spray"
    | "VCT x GEN Spray"
    | "VCT x GE Spray"
    | "VCT x GX Spray"
    | "VCT x KC Spray"
    | "VCT x KOI Spray"
    | "VCT x KRÜ Spray"
    | "VCT x LEV Spray"
    | "VCT x LOUD Spray"
    | "VCT x M8 Spray"
    | "VCT x MIBR Spray"
    | "VCT x NAVI Spray"
    | "VCT x NRG Spray"
    | "VCT x PRX Spray"
    | "VCT x RRQ Spray"
    | "VCT x SEN Spray"
    | "VCT x T1 Spray"
    | "VCT x TH Spray"
    | "VCT x TL Spray"
    | "VCT x TLN Spray"
    | "VCT x TS Spray"
    | "VCT x VIT Spray"
    | "VCT x ZETA Spray"
    | "VCT x AG Spray"
    | "VCT x BLG Spray"
    | "VCT x DRG Spray"
    | "VCT x EDG Spray"
    | "VCT x FPX Spray"
    | "VCT x JDG Spray"
    | "VCT x NOVA Spray"
    | "VCT x TE Spray"
    | "VCT x TEC Spray"
    | "VCT x TYL Spray"
    | "VCT x WOL Spray"
    | "VCT x 2G Spray"
    | "VCT x APK Spray"
    | "VCT x BOOM Spray"
    | "VCT x NS Spray"
    | "VCT x XLG Spray"
    | "5 Years Spray"
    | "Reyna Spray"
    | "Leer Spray"
    | "Marked for Death Spray"
    | "Vandal Life Spray"
    | "Accidental Renaissance Spray"
    | "Omen Spray"
    | "It Hunts Spray"
    | "Dark Focus Spray"
    | "Jett Spray"
    | "Watch This Spray"
    | "You Better Run Spray";