name: Update Valorant Resources

on:
  schedule:
    # every Tuesday at 18:00 UTC
    - cron: '0 18 * * 2'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    concurrency:
      group: valorant-resources-update
      cancel-in-progress: true

    steps:
      # checkout with full history so rebasing the bot branch works
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # set up Node 22 and cache dependencies via Yarn
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'               # caches Yarn cache dir, not node_modules
          cache-dependency-path: '**/yarn.lock'

      # install all deps (including axios) in one go
      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      # run your type-generation/update script
      - name: Update Types
        run: yarn update:types

      # commit any changes under src/resources
      - name: "Create or update Pull Request: resources"
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "chore: update Valorant resources"
          body: |
            This automated PR updates Valorant skins, agents, chroma, sprays, and buddies.
          branch: "bot/update_valorant_resources"
          path: "src/resources"
          author: "ValClientAction <valclient@action.com>"
          commit-message: "chore: update resources (skins, agents, chroma, sprays, buddies)"
          update-pull-request-title-and-body: false  # don't overwrite the title/body on each update

      # commit any changes under src/types onto the same branch
      - name: Add types commit to PR
        uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "bot/update_valorant_resources"
          path: "src/types"
          author: "ValClientAction <valclient@action.com>"
          commit-message: "chore: update types (skins, agents, chroma, sprays, buddies)"
